# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FeaturesManager' do
  
pod 'MJRefresh'
pod 'AFNetworking', '~> 3.0'
pod 'YYKit'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'
pod 'YTKNetwork'
pod 'SDWebImage', '~>3.8'

end


